TheError following the NVidia driver update has been fixed: "error C7616: global variable gl_FragColor is removed after version 420" * Added out layout for FragColor in draw.frag and present.frag and use this instead of gl_FragColor. * Adds 2 bytes to size of Release executable.